// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commands.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type AddParticipantsToChatParams struct {
	ID            pgtype.UUID
	ChatID        pgtype.UUID
	ParticipantID pgtype.UUID
	Role          string
}

const createChat = `-- name: CreateChat :exec
INSERT INTO chats (
    id,
    type,
    name
) VALUES (
  $1, $2, $3
)
`

type CreateChatParams struct {
	ID   pgtype.UUID
	Type string
	Name pgtype.Text
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) error {
	_, err := q.db.Exec(ctx, createChat, arg.ID, arg.Type, arg.Name)
	return err
}

const createInbox = `-- name: CreateInbox :one
INSERT INTO inbox (
    event_id,
    handler,
    executed_at
) VALUES (
  $1, $2, now()
)
ON CONFLICT DO NOTHING
RETURNING id, event_id, handler, executed_at
`

type CreateInboxParams struct {
	EventID pgtype.UUID
	Handler string
}

func (q *Queries) CreateInbox(ctx context.Context, arg CreateInboxParams) (Inbox, error) {
	row := q.db.QueryRow(ctx, createInbox, arg.EventID, arg.Handler)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Handler,
		&i.ExecutedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (
    id,
    sender_id,
    chat_id,
    body,
    reply_to_message_id
) VALUES (
  $1, $2, $3, $4, $5
)
`

type CreateMessageParams struct {
	ID               pgtype.UUID
	SenderID         pgtype.UUID
	ChatID           pgtype.UUID
	Body             string
	ReplyToMessageID pgtype.UUID
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.ID,
		arg.SenderID,
		arg.ChatID,
		arg.Body,
		arg.ReplyToMessageID,
	)
	return err
}

const deleteChat = `-- name: DeleteChat :exec
UPDATE chats
  set deleted_at = $2
WHERE id = $1
`

type DeleteChatParams struct {
	ID        pgtype.UUID
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) DeleteChat(ctx context.Context, arg DeleteChatParams) error {
	_, err := q.db.Exec(ctx, deleteChat, arg.ID, arg.DeletedAt)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
UPDATE messages
  set deleted_at = $2
WHERE id = $1
`

type DeleteMessageParams struct {
	ID        pgtype.UUID
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.Exec(ctx, deleteMessage, arg.ID, arg.DeletedAt)
	return err
}

const processEvent = `-- name: ProcessEvent :exec
UPDATE outbox
  set status = $2,
  claimed_at = $3,
  attempts = $4,
  errors = $5,
  next_retry_at = $6
WHERE id = $1
`

type ProcessEventParams struct {
	ID          pgtype.UUID
	Status      string
	ClaimedAt   pgtype.Timestamptz
	Attempts    int32
	Errors      []string
	NextRetryAt pgtype.Timestamptz
}

func (q *Queries) ProcessEvent(ctx context.Context, arg ProcessEventParams) error {
	_, err := q.db.Exec(ctx, processEvent,
		arg.ID,
		arg.Status,
		arg.ClaimedAt,
		arg.Attempts,
		arg.Errors,
		arg.NextRetryAt,
	)
	return err
}

const putToOutbox = `-- name: PutToOutbox :exec
INSERT INTO outbox (
    id,
    event_id,
    event_type,
    event_payload
) VALUES (
  $1, $2, $3, $4
)
`

type PutToOutboxParams struct {
	ID           pgtype.UUID
	EventID      string
	EventType    string
	EventPayload []byte
}

func (q *Queries) PutToOutbox(ctx context.Context, arg PutToOutboxParams) error {
	_, err := q.db.Exec(ctx, putToOutbox,
		arg.ID,
		arg.EventID,
		arg.EventType,
		arg.EventPayload,
	)
	return err
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
  set body = $2,
  updated_at = $3
WHERE id = $1
`

type UpdateMessageParams struct {
	ID        pgtype.UUID
	Body      string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.db.Exec(ctx, updateMessage, arg.ID, arg.Body, arg.UpdatedAt)
	return err
}
