// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChat = `-- name: GetChat :one
SELECT id, type, name, created_at, deleted_at FROM chats
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChat(ctx context.Context, id pgtype.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEventToProcess = `-- name: GetEventToProcess :one

WITH events_to_process as (
    SELECT id, event_id, event_type, event_payload, occurred_at, status, claimed_at, attempts, errors, next_retry_at FROM outbox
    WHERE status = 'pending'
    OR (status = 'retry' AND now() >= next_retry_at)
    ORDER BY occurred_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE outbox e
SET status = 'processing',
claimed_at = now()
FROM events_to_process ep
WHERE e.id = ep.id
RETURNING e.id, e.event_id, e.event_type, e.event_payload, e.occurred_at, e.status, e.claimed_at, e.attempts, e.errors, e.next_retry_at
`

// -- name: ListUnprocessedEvents :many
// SELECT * FROM outbox
// WHERE processed_at IS NULL
// ORDER BY published_at
// LIMIT 100;
func (q *Queries) GetEventToProcess(ctx context.Context) (Outbox, error) {
	row := q.db.QueryRow(ctx, getEventToProcess)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.EventPayload,
		&i.OccurredAt,
		&i.Status,
		&i.ClaimedAt,
		&i.Attempts,
		&i.Errors,
		&i.NextRetryAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, sender_id, chat_id, body, reply_to_message_id, created_at, updated_at, deleted_at FROM messages
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ChatID,
		&i.Body,
		&i.ReplyToMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listChatsForUser = `-- name: ListChatsForUser :many
SELECT id, type, name, created_at, deleted_at FROM chats
WHERE id = ANY(
    SELECT chat_id
    FROM chat_participants
    WHERE participant_id = $1
)
ORDER BY created_at DESC
LIMIT $2 
OFFSET $3
`

type ListChatsForUserParams struct {
	ParticipantID pgtype.UUID
	Limit         int32
	Offset        int32
}

func (q *Queries) ListChatsForUser(ctx context.Context, arg ListChatsForUserParams) ([]Chat, error) {
	rows, err := q.db.Query(ctx, listChatsForUser, arg.ParticipantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesForChat = `-- name: ListMessagesForChat :many
SELECT id, sender_id, chat_id, body, reply_to_message_id, created_at, updated_at, deleted_at FROM messages
WHERE chat_id = $1
ORDER BY created_at DESC
LIMIT $2 
OFFSET $3
`

type ListMessagesForChatParams struct {
	ChatID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListMessagesForChat(ctx context.Context, arg ListMessagesForChatParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesForChat, arg.ChatID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ChatID,
			&i.Body,
			&i.ReplyToMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const privateChatExists = `-- name: PrivateChatExists :one

SELECT EXISTS (
    SELECT 1 
    FROM chats c
    WHERE c.type = 'private_chat'
    AND EXISTS(SELECT 1 FROM chat_participants cp WHERE cp.chat_id = c.id AND cp.participant_id = $1)
    AND EXISTS(SELECT 1 FROM chat_participants cp WHERE cp.chat_id = c.id AND cp.participant_id = $2)
)
`

type PrivateChatExistsParams struct {
	ParticipantID   pgtype.UUID
	ParticipantID_2 pgtype.UUID
}

// -- name: PrivateChatExists :one
// SELECT 1 FROM private_chats
// WHERE user1_id = $1
// AND user2_id = $2;
func (q *Queries) PrivateChatExists(ctx context.Context, arg PrivateChatExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, privateChatExists, arg.ParticipantID, arg.ParticipantID_2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
