// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        pgtype.UUID
	Type      string
	Name      pgtype.Text
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type ChatParticipant struct {
	ID            pgtype.UUID
	ChatID        pgtype.UUID
	ParticipantID pgtype.UUID
	Role          string
	JoinedAt      pgtype.Timestamptz
}

type Event struct {
	ID           pgtype.UUID
	EventType    string
	EventPayload []byte
	OccurredAt   pgtype.Timestamptz
	Status       string
	ClaimedAt    pgtype.Timestamptz
	Attempts     int32
	Error        pgtype.Text
	NextRetryAt  pgtype.Timestamptz
}

type EventHandlerExecution struct {
	ID          pgtype.UUID
	EventID     pgtype.UUID
	HandlerType string
	Attempts    int32
	Error       pgtype.Text
	NextRetryAt pgtype.Timestamptz
}

type File struct {
	ID        pgtype.UUID
	Hash      []byte
	Name      pgtype.Text
	Url       string
	CreatedAt pgtype.Timestamptz
}

type Message struct {
	ID               pgtype.UUID
	SenderID         pgtype.UUID
	ChatID           pgtype.UUID
	Body             string
	ReplyToMessageID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type MessagesFile struct {
	ID        pgtype.UUID
	MessageID pgtype.UUID
	FileID    pgtype.UUID
	Name      pgtype.Text
}
