services:
  postgres:
    image: postgres:18.4
    restart: always
    shm_size: 128mb
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    networks:
      - mynet
  
  redis:
    image: redis:8.10.1
    restart: always
    shm_size: 128mb
    ports:
      - "6379:6379"
    networks:
      - mynet

volumes:
  postgres:

networks:
  mynet:
    driver: bridge
