// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"messenger/messenger/internal/messaging/application/command/create_private_chat"
	"messenger/messenger/internal/messaging/application/command/send_message"
	"messenger/messenger/internal/messaging/application/event/message_sent"
	"messenger/messenger/internal/messaging/infrastructure/event"
	"messenger/messenger/internal/messaging/infrastructure/outbox_relay"
	"messenger/messenger/internal/messaging/infrastructure/postgres"
	"messenger/messenger/internal/messaging/infrastructure/repositories"
	"messenger/messenger/internal/messaging/infrastructure/sqlc"
	"messenger/messenger/internal/platform/config"
	"messenger/messenger/internal/platform/db"
	"messenger/messenger/internal/platform/db/transaction"
	"messenger/messenger/internal/platform/http_server"
	"messenger/messenger/internal/platform/logger"
)

// Injectors from wire.go:

func InitializeApi() (*Api, func(), error) {
	configConfig := config.Load()
	loggerLogger := logger.New()
	pool, cleanup, err := postgres.NewPool(configConfig)
	if err != nil {
		return nil, nil, err
	}
	manager := transaction.NewManager(pool)
	queries := sqlc.New(pool)
	storage := db.NewStorage(queries)
	eventService := event.NewEventService(storage)
	messageRepository := repositories.NewMessageRepository(queries)
	chatRepository := repositories.NewChatRepository(queries)
	handler := send_message.NewHandler(messageRepository, chatRepository)
	chatParticipantRepository := repositories.NewChatParticipantRepository(queries)
	create_private_chatHandler := create_private_chat.NewHandler(chatRepository, chatParticipantRepository)
	bus := BuildCommandBusForApi(manager, loggerLogger, eventService, handler, create_private_chatHandler)
	controller := http_server.NewController(bus)
	server := http_server.NewServer(configConfig, loggerLogger, controller)
	api := NewApi(server, loggerLogger)
	return api, func() {
		cleanup()
	}, nil
}

func InitializeOutboxRelay() (*outbox_relay.OutboxRelay, func(), error) {
	configConfig := config.Load()
	pool, cleanup, err := postgres.NewPool(configConfig)
	if err != nil {
		return nil, nil, err
	}
	queries := sqlc.New(pool)
	storage := db.NewStorage(queries)
	eventService := event.NewEventService(storage)
	manager := transaction.NewManager(pool)
	loggerLogger := logger.New()
	notifyChatParticipantsHandler := message_sent.NewNotifyChatParticipantsHandler()
	rebuildQueryModelHandler := message_sent.NewRebuildQueryModelHandler()
	handlerRegistry := NewEventHandlerRegistry(notifyChatParticipantsHandler, rebuildQueryModelHandler)
	outboxRelay := outbox_relay.NewOutboxRelay(eventService, manager, loggerLogger, queries, handlerRegistry)
	return outboxRelay, func() {
		cleanup()
	}, nil
}
