// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"messenger/messenger/internal/auth/application/command/login"
	"messenger/messenger/internal/auth/application/command/refresh"
	"messenger/messenger/internal/auth/application/command/register"
	"messenger/messenger/internal/auth/application/query/get_current_user"
	"messenger/messenger/internal/auth/infrastructure/password"
	repository2 "messenger/messenger/internal/auth/infrastructure/repository"
	"messenger/messenger/internal/auth/infrastructure/token"
	"messenger/messenger/internal/messaging/application/command/create_private_chat"
	"messenger/messenger/internal/messaging/application/command/send_message"
	"messenger/messenger/internal/messaging/application/event/message_sent"
	"messenger/messenger/internal/messaging/application/query/get_chat_list"
	"messenger/messenger/internal/messaging/infrastructure/event"
	"messenger/messenger/internal/messaging/infrastructure/outbox_relay"
	repository3 "messenger/messenger/internal/messaging/infrastructure/repository"
	"messenger/messenger/internal/messaging/infrastructure/sqlc"
	"messenger/messenger/internal/platform/config"
	"messenger/messenger/internal/platform/db"
	"messenger/messenger/internal/platform/db/transaction"
	"messenger/messenger/internal/platform/http_server"
	"messenger/messenger/internal/platform/logger"
	"messenger/messenger/internal/platform/postgres"
	"messenger/messenger/internal/platform/querybus"
	"messenger/messenger/internal/shared/infrastructure/repository"
)

// Injectors from wire.go:

func InitializeApi() (*Api, func(), error) {
	configConfig := config.Load()
	loggerLogger := logger.New()
	pool, cleanup, err := postgres.NewPool(configConfig)
	if err != nil {
		return nil, nil, err
	}
	manager := transaction.NewManager(pool)
	queries := sqlc.New(pool)
	storage := db.NewStorage(queries)
	eventService := event.NewEventService(storage)
	repositoryRepository := repository.NewRepository(storage)
	userRepository := repository2.NewUserRepository(repositoryRepository)
	sessionRepository := repository2.NewSessionRepository(repositoryRepository)
	hasher := password.NewHasher(configConfig)
	service, err := token.NewService()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	handler := register.NewHandler(userRepository, sessionRepository, hasher, service)
	loginHandler := login.NewHandler(userRepository, sessionRepository, hasher, service)
	refreshHandler := refresh.NewHandler(sessionRepository, service)
	messageRepository := repository3.NewMessageRepository(repositoryRepository)
	chatRepository := repository3.NewChatRepository(repositoryRepository)
	send_messageHandler := send_message.NewHandler(messageRepository, chatRepository)
	chatParticipantRepository := repository3.NewChatParticipantRepository(repositoryRepository)
	create_private_chatHandler := create_private_chat.NewHandler(chatRepository, chatParticipantRepository)
	bus := BuildCommandBus(manager, loggerLogger, eventService, handler, loginHandler, refreshHandler, send_messageHandler, create_private_chatHandler)
	get_current_userHandler := get_current_user.NewHandler()
	get_chat_listHandler := get_chat_list.NewHandler()
	querybusBus := querybus.InitBus(get_current_userHandler, get_chat_listHandler)
	controller := http_server.NewController(bus, querybusBus)
	server := http_server.NewServer(configConfig, loggerLogger, controller, service)
	api := NewApi(server, loggerLogger)
	return api, func() {
		cleanup()
	}, nil
}

func InitializeOutboxRelay() (*outbox_relay.OutboxRelay, func(), error) {
	configConfig := config.Load()
	pool, cleanup, err := postgres.NewPool(configConfig)
	if err != nil {
		return nil, nil, err
	}
	queries := sqlc.New(pool)
	storage := db.NewStorage(queries)
	eventService := event.NewEventService(storage)
	manager := transaction.NewManager(pool)
	loggerLogger := logger.New()
	notifyChatParticipantsHandler := message_sent.NewNotifyChatParticipantsHandler()
	rebuildQueryModelHandler := message_sent.NewRebuildQueryModelHandler()
	handlerRegistry := NewEventHandlerRegistry(notifyChatParticipantsHandler, rebuildQueryModelHandler)
	outboxRelay := outbox_relay.NewOutboxRelay(eventService, manager, loggerLogger, queries, handlerRegistry)
	return outboxRelay, func() {
		cleanup()
	}, nil
}
