// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commands.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AddParticipantsToChatParams struct {
	ID            uuid.UUID
	ChatID        uuid.NullUUID
	ParticipantID uuid.UUID
	Role          string
}

const createChat = `-- name: CreateChat :exec
INSERT INTO messaging.chats (
    id,
    kind,
    name
) VALUES (
  $1, $2, $3
)
`

type CreateChatParams struct {
	ID   uuid.UUID
	Kind string
	Name pgtype.Text
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) error {
	_, err := q.db.Exec(ctx, createChat, arg.ID, arg.Kind, arg.Name)
	return err
}

const createInbox = `-- name: CreateInbox :one
INSERT INTO inbox (
    event_id,
    handler,
    executed_at
) VALUES (
  $1, $2, now()
)
ON CONFLICT DO NOTHING
RETURNING id, event_id, handler, executed_at
`

type CreateInboxParams struct {
	EventID string
	Handler string
}

func (q *Queries) CreateInbox(ctx context.Context, arg CreateInboxParams) (Inbox, error) {
	row := q.db.QueryRow(ctx, createInbox, arg.EventID, arg.Handler)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Handler,
		&i.ExecutedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messaging.messages (
    id,
    sender_id,
    chat_id,
    body,
    reply_to_message_id
) VALUES (
  $1, $2, $3, $4, $5
)
`

type CreateMessageParams struct {
	ID               uuid.UUID
	SenderID         uuid.UUID
	ChatID           uuid.UUID
	Body             string
	ReplyToMessageID uuid.NullUUID
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.ID,
		arg.SenderID,
		arg.ChatID,
		arg.Body,
		arg.ReplyToMessageID,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO auth.sessions (
  id,
  user_id,
  refresh_token_hash,
  expires_at,
  user_agent,
  ip
) VALUES (
  $1, $2, $3, $4, $5, $6
)
`

type CreateSessionParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	UserAgent        string
	Ip               netip.Addr
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO auth.users (
  id,
  login,
  password_hash
) VALUES (
  $1, $2, $3
)
`

type CreateUserParams struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.Login, arg.PasswordHash)
	return err
}

const deleteChat = `-- name: DeleteChat :exec
UPDATE messaging.chats
  set deleted_at = $2
WHERE id = $1
`

type DeleteChatParams struct {
	ID        uuid.UUID
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) DeleteChat(ctx context.Context, arg DeleteChatParams) error {
	_, err := q.db.Exec(ctx, deleteChat, arg.ID, arg.DeletedAt)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
UPDATE messaging.messages
  set deleted_at = $2
WHERE id = $1
`

type DeleteMessageParams struct {
	ID        uuid.UUID
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.Exec(ctx, deleteMessage, arg.ID, arg.DeletedAt)
	return err
}

const processEvent = `-- name: ProcessEvent :exec
UPDATE outbox
  set status = $2,
  claimed_at = $3,
  attempts = $4,
  errors = $5,
  next_retry_at = $6
WHERE id = $1
`

type ProcessEventParams struct {
	ID          uuid.UUID
	Status      string
	ClaimedAt   pgtype.Timestamptz
	Attempts    int32
	Errors      []string
	NextRetryAt pgtype.Timestamptz
}

func (q *Queries) ProcessEvent(ctx context.Context, arg ProcessEventParams) error {
	_, err := q.db.Exec(ctx, processEvent,
		arg.ID,
		arg.Status,
		arg.ClaimedAt,
		arg.Attempts,
		arg.Errors,
		arg.NextRetryAt,
	)
	return err
}

const putToOutbox = `-- name: PutToOutbox :exec
INSERT INTO outbox (
    id,
    event_id,
    event_type,
    event_payload
) VALUES (
  $1, $2, $3, $4
)
`

type PutToOutboxParams struct {
	ID           uuid.UUID
	EventID      string
	EventType    string
	EventPayload []byte
}

func (q *Queries) PutToOutbox(ctx context.Context, arg PutToOutboxParams) error {
	_, err := q.db.Exec(ctx, putToOutbox,
		arg.ID,
		arg.EventID,
		arg.EventType,
		arg.EventPayload,
	)
	return err
}

const saveSession = `-- name: SaveSession :exec
UPDATE auth.sessions
SET refresh_token_hash = $2,
  expires_at = $3,
  revoked_at = $4,
  last_used_at = $5
WHERE id = $1
`

type SaveSessionParams struct {
	ID               uuid.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
}

func (q *Queries) SaveSession(ctx context.Context, arg SaveSessionParams) error {
	_, err := q.db.Exec(ctx, saveSession,
		arg.ID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.LastUsedAt,
	)
	return err
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messaging.messages
  set body = $2,
  updated_at = $3
WHERE id = $1
`

type UpdateMessageParams struct {
	ID        uuid.UUID
	Body      string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.db.Exec(ctx, updateMessage, arg.ID, arg.Body, arg.UpdatedAt)
	return err
}
