// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForAddParticipantsToChat implements pgx.CopyFromSource.
type iteratorForAddParticipantsToChat struct {
	rows                 []AddParticipantsToChatParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddParticipantsToChat) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddParticipantsToChat) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ChatID,
		r.rows[0].ParticipantID,
		r.rows[0].Role,
	}, nil
}

func (r iteratorForAddParticipantsToChat) Err() error {
	return nil
}

func (q *Queries) AddParticipantsToChat(ctx context.Context, arg []AddParticipantsToChatParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"messaging", "chat_participants"}, []string{"id", "chat_id", "participant_id", "role"}, &iteratorForAddParticipantsToChat{rows: arg})
}
