// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	CreatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
	Device           string
	Ip               netip.Addr
}

type AuthUser struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
	Name         pgtype.Text
	CreatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type Inbox struct {
	ID         uuid.UUID
	EventID    string
	Handler    string
	ExecutedAt pgtype.Timestamptz
}

type MessagingChat struct {
	ID        uuid.UUID
	Kind      string
	Name      pgtype.Text
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type MessagingChatParticipant struct {
	ID            uuid.UUID
	ChatID        uuid.NullUUID
	ParticipantID uuid.UUID
	Role          string
	JoinedAt      pgtype.Timestamptz
}

type MessagingFile struct {
	ID        uuid.UUID
	Hash      []byte
	Name      pgtype.Text
	Url       string
	CreatedAt pgtype.Timestamptz
}

type MessagingMessage struct {
	ID               uuid.UUID
	SenderID         uuid.UUID
	ChatID           uuid.UUID
	Body             string
	ReplyToMessageID uuid.NullUUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type MessagingMessageFile struct {
	ID        uuid.UUID
	MessageID uuid.NullUUID
	FileID    uuid.NullUUID
	Name      pgtype.Text
}

type Outbox struct {
	ID           uuid.UUID
	EventID      string
	EventType    string
	EventPayload []byte
	OccurredAt   pgtype.Timestamptz
	Status       string
	ClaimedAt    pgtype.Timestamptz
	Attempts     int32
	Errors       []string
	NextRetryAt  pgtype.Timestamptz
}
