// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getChat = `-- name: GetChat :one
SELECT id, kind, name, created_at, deleted_at FROM messaging.chats
WHERE id = $1
`

func (q *Queries) GetChat(ctx context.Context, id uuid.UUID) (MessagingChat, error) {
	row := q.db.QueryRow(ctx, getChat, id)
	var i MessagingChat
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEventToProcess = `-- name: GetEventToProcess :one
WITH events_to_process as (
    SELECT id, event_id, event_type, event_payload, occurred_at, status, claimed_at, attempts, errors, next_retry_at FROM outbox
    WHERE status = 'pending'
    OR (status = 'retry' AND now() >= next_retry_at)
    ORDER BY occurred_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE outbox e
SET status = 'processing',
claimed_at = now()
FROM events_to_process ep
WHERE e.id = ep.id
RETURNING e.id, e.event_id, e.event_type, e.event_payload, e.occurred_at, e.status, e.claimed_at, e.attempts, e.errors, e.next_retry_at
`

func (q *Queries) GetEventToProcess(ctx context.Context) (Outbox, error) {
	row := q.db.QueryRow(ctx, getEventToProcess)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.EventPayload,
		&i.OccurredAt,
		&i.Status,
		&i.ClaimedAt,
		&i.Attempts,
		&i.Errors,
		&i.NextRetryAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, sender_id, chat_id, body, reply_to_message_id, created_at, updated_at, deleted_at FROM messaging.messages
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (MessagingMessage, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i MessagingMessage
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ChatID,
		&i.Body,
		&i.ReplyToMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, refresh_token_hash, created_at, expires_at, revoked_at, last_used_at, device, ip FROM auth.sessions
WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.Device,
		&i.Ip,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, password_hash, name, created_at, deleted_at FROM auth.users
WHERE login = $1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listChatsForUser = `-- name: ListChatsForUser :many
SELECT id, kind, name, created_at, deleted_at FROM messaging.chats
WHERE id = ANY(
    SELECT chat_id
    FROM messaging.chat_participants
    WHERE participant_id = $1
)
ORDER BY created_at DESC
LIMIT $2 
OFFSET $3
`

type ListChatsForUserParams struct {
	ParticipantID uuid.UUID
	Limit         int32
	Offset        int32
}

func (q *Queries) ListChatsForUser(ctx context.Context, arg ListChatsForUserParams) ([]MessagingChat, error) {
	rows, err := q.db.Query(ctx, listChatsForUser, arg.ParticipantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagingChat
	for rows.Next() {
		var i MessagingChat
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesForChat = `-- name: ListMessagesForChat :many
SELECT id, sender_id, chat_id, body, reply_to_message_id, created_at, updated_at, deleted_at FROM messaging.messages
WHERE chat_id = $1
ORDER BY created_at DESC
LIMIT $2 
OFFSET $3
`

type ListMessagesForChatParams struct {
	ChatID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListMessagesForChat(ctx context.Context, arg ListMessagesForChatParams) ([]MessagingMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesForChat, arg.ChatID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagingMessage
	for rows.Next() {
		var i MessagingMessage
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ChatID,
			&i.Body,
			&i.ReplyToMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const privateChatExists = `-- name: PrivateChatExists :one
SELECT EXISTS(
    SELECT 1 
    FROM messaging.chats c
    WHERE c.kind = 'private_chat'
    AND EXISTS(SELECT 1 FROM messaging.chat_participants cp WHERE cp.chat_id = c.id AND cp.participant_id = $1)
    AND EXISTS(SELECT 1 FROM messaging.chat_participants cp WHERE cp.chat_id = c.id AND cp.participant_id = $2)
)
`

type PrivateChatExistsParams struct {
	ParticipantID   uuid.UUID
	ParticipantID_2 uuid.UUID
}

func (q *Queries) PrivateChatExists(ctx context.Context, arg PrivateChatExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, privateChatExists, arg.ParticipantID, arg.ParticipantID_2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsByLogin = `-- name: UserExistsByLogin :one
SELECT EXISTS(
    SELECT 1 
    FROM auth.users
    WHERE login = $1
)
`

func (q *Queries) UserExistsByLogin(ctx context.Context, login string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByLogin, login)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
