// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"messenger/messenger/internal/adapters/out/logger"
	"messenger/messenger/internal/adapters/out/postgres/queries"
	"messenger/messenger/internal/adapters/out/postgres/repositories"
	"messenger/messenger/internal/adapters/out/postgres/transaction"
	"messenger/messenger/internal/adapters/out/uuid"
	"messenger/messenger/internal/application/command/send_message"
	"messenger/messenger/internal/platform/config"
	"messenger/messenger/internal/platform/event"
	"messenger/messenger/internal/platform/http_server"
	"messenger/messenger/internal/platform/postgres"
)

// Injectors from wire.go:

func InitializeApi() (*Container, func(), error) {
	configConfig := config.Load()
	db, cleanup, err := postgres.NewPool(configConfig)
	if err != nil {
		return nil, nil, err
	}
	manager := transaction.NewManager(db)
	loggerLogger := logger.New()
	queriesQueries := queries.New(db)
	eventStorage := event.NewEventStorage(queriesQueries)
	messageRepository := repositories.NewMessageRepository(db, queriesQueries)
	provider := uuid.NewProvider()
	handler := send_message.NewHandler(messageRepository, provider)
	bus := BuildCommandBusForApi(manager, loggerLogger, eventStorage, handler)
	eventBus := event.NewBus()
	controller := http_server.NewController(bus)
	server := http_server.NewServer(configConfig, controller)
	container := NewContainer(db, manager, bus, eventBus, handler, messageRepository, server, loggerLogger)
	return container, func() {
		cleanup()
	}, nil
}
