// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"messenger/messenger/internal/adapters/out/logger"
	"messenger/messenger/internal/adapters/out/postgres/repositories"
	"messenger/messenger/internal/adapters/out/postgres/transaction"
	"messenger/messenger/internal/adapters/out/uuid"
	"messenger/messenger/internal/application/command/create_private_chat"
	"messenger/messenger/internal/application/command/send_message"
	"messenger/messenger/internal/application/event/message_sent"
	"messenger/messenger/internal/platform/config"
	"messenger/messenger/internal/platform/db"
	"messenger/messenger/internal/platform/event"
	"messenger/messenger/internal/platform/http_server"
	"messenger/messenger/internal/platform/postgres"
)

// Injectors from wire.go:

func InitializeApi() (*Api, func(), error) {
	configConfig := config.Load()
	pool, cleanup, err := postgres.NewPool(configConfig)
	if err != nil {
		return nil, nil, err
	}
	manager := transaction.NewManager(pool)
	loggerLogger := logger.New()
	queries := db.New(pool)
	storage := db.NewStorage(queries)
	eventStorage := event.NewEventStorage(storage)
	messageRepository := repositories.NewMessageRepository(queries)
	provider := uuid.NewProvider()
	handler := send_message.NewHandler(messageRepository, provider)
	chatRepository := repositories.NewChatRepository(queries)
	chatParticipantRepository := repositories.NewChatParticipantRepository(queries)
	create_private_chatHandler := create_private_chat.NewHandler(chatRepository, chatParticipantRepository, provider)
	bus := BuildCommandBusForApi(manager, loggerLogger, eventStorage, handler, create_private_chatHandler)
	controller := http_server.NewController(bus)
	server := http_server.NewServer(configConfig, controller)
	api := NewApi(server, loggerLogger)
	return api, func() {
		cleanup()
	}, nil
}

func InitializeEventProcessor() (*event.Processor, func(), error) {
	configConfig := config.Load()
	pool, cleanup, err := postgres.NewPool(configConfig)
	if err != nil {
		return nil, nil, err
	}
	queries := db.New(pool)
	storage := db.NewStorage(queries)
	eventStorage := event.NewEventStorage(storage)
	manager := transaction.NewManager(pool)
	loggerLogger := logger.New()
	notifyChatParticipantsHandler := message_sent.NewNotifyChatParticipantsHandler()
	bus, err := BuildEventBusForProcessor(notifyChatParticipantsHandler)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	processor := event.NewProcessor(eventStorage, manager, loggerLogger, queries, bus)
	return processor, func() {
		cleanup()
	}, nil
}
