// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"messenger/messenger/internal/adapters/out/postgres/queries"
	"messenger/messenger/internal/adapters/out/postgres/repositories"
	"messenger/messenger/internal/adapters/out/postgres/transaction"
	"messenger/messenger/internal/adapters/out/uuid"
	"messenger/messenger/internal/application/command/send_message"
	"messenger/messenger/internal/platform/command"
	"messenger/messenger/internal/platform/event"
	"messenger/messenger/internal/platform/postgres"
)

// Injectors from wire.go:

func InitializeContainer(ctx context.Context) (*Container, func(), error) {
	db, cleanup, err := postgres.NewPool(ctx)
	if err != nil {
		return nil, nil, err
	}
	manager := transaction.NewManager(db)
	bus := command.NewBus()
	eventBus := event.NewBus()
	queriesQueries := queries.New(db)
	messageRepository := repositories.NewMessageRepository(db, queriesQueries)
	provider := uuid.NewProvider()
	handler := send_message.NewHandler(messageRepository, provider)
	container := NewContainer(db, manager, bus, eventBus, handler, messageRepository)
	return container, func() {
		cleanup()
	}, nil
}
