Auth:
  JWT:
    PrivateKey: /etc/app/keys/jwt-private.pem
    PublicKey: /etc/app/keys/jwt-public.pem

Database:
  Driver: pgx
  Schema: postgres
  Host: localhost
  Port: 5432
  Name: app
  User:
  Password:

HttpServer:
  Addr: :3000
